server:
  servlet:
    context-path: /srk
  port: 9090 # Spring-boot's default port is 8080 for http and 8443 for https
spring:
  main:
    banner-mode: 'off' # It should be in quotes yaml
# H2-DB props    
  h2:
    console:
      enabled: true
      path: /h2db-console
  jpa:
    hibernate:
      ddl-auto: none # this option will turn-off DDL generation