server:
  servlet:
    context-path: /srk
  port: 9090 # Spring-boot's default port is 8080 for http and 8443 for https
spring:
  main:
    banner-mode: 'off' # It should be in quotes yaml
  datasource:
    url: jdbc:h2:mem:testdb # This propperty is implict and default for h2, but adding here for reference to know the db-name and h2-db mode of connection
# H2-DB props
  h2:
    console:
      enabled: true
      path: /h2db-console    
  jpa:
    hibernate:
      ddl-auto: none # this option will turn-off DDL generation            